//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageExtension { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<bool> IsMain { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
