//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.DetailReceipts = new HashSet<DetailReceipt>();
        }
    
        public int ReceiptId { get; set; }
        public Nullable<System.DateTime> dates { get; set; }
        public Nullable<int> Total { get; set; }
        public string CustomerUsername { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public string CustomerName { get; set; }
        public string AddressReceipt { get; set; }
        public string PhoneCus { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailReceipt> DetailReceipts { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual StatusRC StatusRC { get; set; }
    }
}
